### ISSUE TITLE
Change font color

### ISSUE THREAD

**Issue by ehayun** [buren/chartkick-ex#23]
Thanks for your great job
I am wondering, if there is a way to change the font color?
I am using black background and the text is hard to read

Another question: Is there a way to put a text at the top left corner of a line chart?

Thanks again

**Comment by buren** [comment]
Hi @ehayun,

You should be able to achieve this using `chartkick.js`s `library` option,. (I found [this on stackoverflow](https://stackoverflow.com/questions/48411739/chartkick-chart-js-change-colour-of-axis-and-colour-of-axis-title)) You have to pass options to `library` since it depends on what underlying chart library you use chart.js vs highcharts.js vs google charts.

`chartkick-ex` supports the `library` option and there is even an example in the [README](https://github.com/buren/chartkick-ex/blob/master/README.md) where you customize the background color like this 👇 
```elixir
Chartkick.line_chart data, library: %{ backgroundColor: "#eee" }
```

Hope that helps.

**Comment by ehayun** [comment]
Thanks
Didn't work, it will affected the graph itself but not the background or the yTitle color

Thanks anywhay
